# Generated by Django 2.2.3 on 2019-07-29 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolie',
            new_name='Portfolio',
        ),
    ]
